#!/usr/bin/env bash
# comment goes here.

echo " " 
echo " "
cat /root/checker_files/2167/20040/main_12.c
echo " " 
echo " " 
cat /root/checker_files/2167/20040/main_13.c
echo " " 
echo " "
ls /root/checker_files/2167/20040
