#!/usr/bin/env bash
# comment goes here.

echo " " 
echo " "
cat /root/checker_files/2167/20040/main_10.c
echo " " 
echo " " 
cat /root/checker_files/2167/20040/main_11.c
echo " " 
echo " "
ls /root/checker_files/2167/20040
